osx_image: xcode7.3

sudo: required

language: c

matrix:
  include:
    - os: osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 6
- npm install electron-builder@next # force install next version to test electron-builder
- npm install
- npm prune

script:
- npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
